version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quartermaster_postgres
    restart: always
    environment:
      POSTGRES_USER: quartermaster
      POSTGRES_PASSWORD: q123@#
      POSTGRES_DB: quartermasterdb
    ports:
      - "5433:5432"  # Host:Container port mapping
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: quartermaster_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@quartermaster.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5051:80"  # pgAdmin accessible at localhost:5050
    depends_on:
      - db

volumes:
  postgres_data:
